// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlhhlLCpXc_LbN4CPEoXSSgG_O5jwUMog',
    appId: '1:38368136572:android:6ce41c47fefee5571068f9',
    messagingSenderId: '38368136572',
    projectId: 'fir-55b43',
    storageBucket: 'fir-55b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Eon9tAQ-dHNN27pMwFuXGXiuEnej1K8',
    appId: '1:38368136572:ios:778cc582a8f46cd81068f9',
    messagingSenderId: '38368136572',
    projectId: 'fir-55b43',
    storageBucket: 'fir-55b43.appspot.com',
    iosClientId: '38368136572-36pvlj982cn76dnvtr0fi8lbgbcb124l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Eon9tAQ-dHNN27pMwFuXGXiuEnej1K8',
    appId: '1:38368136572:ios:778cc582a8f46cd81068f9',
    messagingSenderId: '38368136572',
    projectId: 'fir-55b43',
    storageBucket: 'fir-55b43.appspot.com',
    iosClientId: '38368136572-36pvlj982cn76dnvtr0fi8lbgbcb124l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
